### ISSUE TITLE
Pylint false positive: no name in module

### ISSUE THREAD

**Issue by jasperfirecai2** [messense/nh3#18]
![image](https://github.com/messense/nh3/assets/8398131/5ebe5452-9ea2-42ed-980f-8703a6c77940)
Is there a linter plugin to install, or is the module improperly configured for pylint? Functionally this code works perfectly, and intellisense can see that it's fine.

**Comment by messense** [comment]
So intellisense is fine, the problem is on the pylint side, try ask pylint for help: https://pylint.readthedocs.io/en/latest/contact.html
