### ISSUE TITLE
 Line endings \r\n converted to \n

### ISSUE THREAD

**Issue by stella-councyl** [messense/nh3#51]
Hi, 

When I use `nh3.clean()`, line endings `\r\n` are converted to `\n`. 
This behavior can cause issues for applications that rely on `\r\n` as their newline format, for example in a request body.

Example code
```
import nh3

input = "Line1\r\nLine2"
nh3.clean(input) # Outputs: 'Line1\nLine2'
```
Is this a desired behavior?

Thank you in advance!
___
Environment:
- nh3 version: 0.2.18
- Python version: 3.12.2
- Operating System: Microsoft Windows [Version 10.0.19045.4651]

**Comment by messense** [comment]
I think this is expected and is out of control on our end (it's done by https://github.com/rust-ammonia/ammonia).
