### ISSUE TITLE
Would it be possible to disable adding of rel="noopener noreferrer"?

### ISSUE THREAD

**Issue by nijel** [messense/nh3#8]
Adding `rel="noopener noreferrer"` to all `<a>` tags is not desired in our use case. Would it be possible to add a parameter to disable that?

If I read ammonia source correctly, it should be achievable by `Builder.link_rel(None)`, so it just needs a way to expose this in the Python interface.

**Comment by messense** [comment]
Sure, it should be relatively easy to expose.

**Comment by messense** [comment]
Added in v0.2.3, example:

```python
assert (
    nh3.clean('<a href="https://google.com">google</a>', link_rel=None)
    == '<a href="https://google.com">google</a>'
)
```
